# Generated by Django 4.2.7 on 2023-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_avater_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
